-- Create hospgeninfo table
CREATE TABLE hospgeninfo (
index TEXT, 
Provider_ID TEXT, 
Hospital_Name TEXT, 
Address TEXT, 
City TEXT, 
State TEXT, 
ZIP_Code TEXT, 
County_Name TEXT, 
Phone_Number TEXT, 
Hospital_Type TEXT, 
Hospital_Ownership TEXT, 
Emergency_Services TEXT, 
Meets_criteria_for_meaningful_use_of_EHRs TEXT, 
Hospital_overall_rating TEXT, 
Hospital_overall_rating_footnote TEXT, 
Mortality_national_comparison TEXT, 
Mortality_national_comparison_footnote TEXT, 
Safety_of_care_national_comparison TEXT, 
Safety_of_care_national_comparison_footnote TEXT, 
Readmission_national_comparison TEXT, 
Readmission_national_comparison_footnote TEXT, 
Patient_experience_national_comparison TEXT, 
Patient_experience_national_comparison_footnote TEXT, 
Effectiveness_of_care_national_comparison TEXT, 
Effectiveness_of_care_national_comparison_footnote TEXT, 
Timeliness_of_care_national_comparison TEXT, 
Timeliness_of_care_national_comparison_footnote TEXT, 
Efficient_use_of_medical_imaging_national_comparison TEXT, 
Efficient_use_of_medical_imaging_national_comparison_footnote TEXT, 
Location TEXT);

-- Create hosploc Table
CREATE TABLE hosploc (
index TEXT,
X TEXT,
Y TEXT,
OBJECTID TEXT,
ID TEXT,
NAME TEXT,
ADDRESS TEXT,
CITY TEXT,
STATE TEXT,
ZIP TEXT,
ZIP4 TEXT,
TELEPHONE TEXT,
TYPE TEXT,
STATUS TEXT,
POPULATION TEXT,
COUNTY TEXT,
COUNTYFIPS TEXT,
COUNTRY TEXT,
LATITUDE TEXT,
LONGITUDE TEXT,
NAICS_CODE TEXT,
NAICS_DESC TEXT,
SOURCE TEXT,
SOURCEDATE TEXT,
VAL_METHOD TEXT,
VAL_DATE TEXT,
WEBSITE TEXT,
STATE_ID TEXT,
ALT_NAME TEXT,
ST_FIPS TEXT,
OWNER TEXT,
TTL_STAFF TEXT,
BEDS TEXT,
TRAUMA TEXT,
HELIPAD TEXT
);

-- Import data into hospgeninfo table - c:\temp directory reference is from my computer
COPY hospgeninfo (index, 
Provider_ID, 
Hospital_Name, 
Address, 
City, 
State, 
ZIP_Code, 
County_Name, 
Phone_Number, 
Hospital_Type, 
Hospital_Ownership, 
Emergency_Services, 
Meets_criteria_for_meaningful_use_of_EHRs, 
Hospital_overall_rating, 
Hospital_overall_rating_footnote, 
Mortality_national_comparison, 
Mortality_national_comparison_footnote, 
Safety_of_care_national_comparison, 
Safety_of_care_national_comparison_footnote, 
Readmission_national_comparison, 
Readmission_national_comparison_footnote, 
Patient_experience_national_comparison, 
Patient_experience_national_comparison_footnote, 
Effectiveness_of_care_national_comparison, 
Effectiveness_of_care_national_comparison_footnote, 
Timeliness_of_care_national_comparison, 
Timeliness_of_care_national_comparison_footnote, 
Efficient_use_of_medical_imaging_national_comparison, 
Efficient_use_of_medical_imaging_national_comparison_footnote, 
Location) 
FROM 'C:\temp\HospitalGeneralInformation.csv' DELIMITER ',' CSV HEADER;

-- Import data into hosploc table - c:\temp directory reference is from my computer
COPY hospgeninfo (
index,
X,
Y,
OBJECTID,
ID,
NAME,
ADDRESS,
CITY,
STATE,
ZIP,
ZIP4,
TELEPHONE,
TYPE,
STATUS,
POPULATION,
COUNTY,
COUNTYFIPS,
COUNTRY,
LATITUDE,
LONGITUDE,
NAICS_CODE,
NAICS_DESC,
SOURCE,
SOURCEDATE,
VAL_METHOD,
VAL_DATE,
WEBSITE,
STATE_ID,
ALT_NAME,
ST_FIPS,
OWNER,
TTL_STAFF,
BEDS,
TRAUMA,
HELIPAD
) 
FROM 'C:\temp\HospitalLocations.csv' DELIMITER ',' CSV HEADER;